Added Modrinth4J
modrinth/awesome pull request #19
Opened 2022-12-17 20:29 UTC by masecla22

:wave:

2022-12-17 20:43 UTC, triphora requested changes

2022-12-17 20:43 UTC, triphora commented on README.md
> +- **[masecla22/Modrinth4J](https://github.com/masecla22/Modrinth4J)** - A fluent CompletableFuture-based Java wrapper for the Modrinth API
Please put it in order

2022-12-18 18:20 UTC, masecla22 commented
Sorry, didn't notice they were ordered alphabetically!

All fixed

2022-12-18 18:21 UTC, triphora approved these changes

2022-12-18 18:21 UTC, merged